# 1. 매출데이터 구축

## 파일 불러오기

In [1]:
import os

# 필요한 파일의 리스트를 만듭니다.

path_dir = 'C:/Users/CSEL/workspace/jupyter_programming/lesson/invest_data_anal/data/'
folder_list = os.listdir(path_dir)
file_list = [os.listdir(path_dir+folder)[2] for folder in folder_list]
print(file_list)

['2016_1분기보고서_03_포괄손익계산서_20210317.txt', '2016_반기보고서_03_포괄손익계산서_20210317.txt', '2016_3분기보고서_03_포괄손익계산서_20210317.txt', '2016_사업보고서_03_포괄손익계산서_20210825.txt', '2017_1분기보고서_03_포괄손익계산서_20210901.txt', '2017_반기보고서_03_포괄손익계산서_20210901.txt', '2017_3분기보고서_03_포괄손익계산서_20210901.txt', '2017_사업보고서_03_포괄손익계산서_20210901.txt', '2018_1분기보고서_03_포괄손익계산서_20210901.txt', '2018_반기보고서_03_포괄손익계산서_20210901.txt', '2018_3분기보고서_03_포괄손익계산서_20210901.txt', '2018_사업보고서_03_포괄손익계산서_20210901.txt', '2019_1분기보고서_03_포괄손익계산서_20210901.txt', '2019_반기보고서_03_포괄손익계산서_20210901.txt', '2019_3분기보고서_03_포괄손익계산서_20210701.txt', '2019_사업보고서_03_포괄손익계산서_20210818.txt', '2020_1분기보고서_03_포괄손익계산서_20210620.txt', '2020_반기보고서_03_포괄손익계산서_20210818.txt', '2020_3분기보고서_03_포괄손익계산서_20210708.txt', '2020_사업보고서_03_포괄손익계산서_20210902.txt', '2021_1분기보고서_03_포괄손익계산서_20210908.txt', '2021_반기보고서_03_포괄손익계산서_20210902.txt']

## 파일 합치기

In [2]:
import pandas as pd
from tqdm import tqdm

# 파일을 읽고 데이터 프레임으로 합칩니다.

df = pd.DataFrame()
for i in tqdm(range(len(file_list))):
    filepath = path_dir + folder_list[i] + '/' + file_list[i]
    df_raw = pd.read_csv(filepath, sep='\t', encoding='cp949')
    df = pd.concat([df, df_raw])
df

100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:17<00:00,  1.23it/s]

,재무제표종류,종목코드,회사명,시장구분,업종,업종명,결산월,결산기준일,보고서종류,통화,...,전기 반기 누적,당기 3분기 3개월,당기 3분기 누적,전기 3분기 3개월,전기 3분기 누적,Unnamed: 12,당기,Unnamed: 14,Unnamed: 15,Unnamed: 18
0,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43415,"포괄손익계산서, 성격별 분류(세전기타포괄손익) - 별도재무제표(선택)",[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-06-30,반기보고서,KRW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43416,"포괄손익계산서, 성격별 분류(세전기타포괄손익) - 별도재무제표(선택)",[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-06-30,반기보고서,KRW,...,"18,294,058,308",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43417,"포괄손익계산서, 성격별 분류(세전기타포괄손익) - 별도재무제표(선택)",[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-06-30,반기보고서,KRW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43418,"포괄손익계산서, 성격별 분류(세전기타포괄손익) - 별도재무제표(선택)",[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-06-30,반기보고서,KRW,...,"3,142",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43419,"포괄손익계산서, 성격별 분류(세전기타포괄손익) - 별도재무제표(선택)",[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-06-30,반기보고서,KRW,...,"3,142",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 데이터 전처리

In [3]:
# 코스닥만 가져옵니다.

df = df[df['시장구분'].isin(['코스닥시장상장법인'])]
len(df['회사명'].unique()) # 코스닥 상장 회사의 개수입니다.

1800

In [4]:
# 현재 데이터에 매출액이 여러가지 이름으로 되어있습니다. 이를 바꿔줍니다.

df.replace({'수익(매출액)': '매출액', '매출':'매출액'}, inplace=True)

C:\Users\CSEL\anaconda3\lib\site-packages\pandas\core\frame.py:4524: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [5]:
# 항목명이 매출액인 부분만 가져옵니다.

df = df[df['항목명'].isin(['매출액'])]
df['당기 1분기 3개월']

0          5,975,861,071
74        35,352,899,194
92         2,236,550,468
157       48,093,649,629
208      289,597,782,947
              ...
43301                NaN
43319                NaN
43335                NaN
43384                NaN
43401                NaN
Name: 당기 1분기 3개월, Length: 23526, dtype: object

In [6]:
# 각 열마다 눌값이 있다는 것을 확인합니다.

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23526 entries, 0 to 43401
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   재무제표종류       23526 non-null  object
 1   종목코드         23526 non-null  object
 2   회사명          23526 non-null  object
 3   시장구분         23526 non-null  object
 4   업종           23526 non-null  int64
 5   업종명          23526 non-null  object
 6   결산월          23526 non-null  int64
 7   결산기준일        23526 non-null  object
 8   보고서종류        23526 non-null  object
 9   통화           23526 non-null  object
 10  항목코드         23526 non-null  object
 11  항목명          23526 non-null  object
 12  당기 1분기 3개월   6373 non-null   object
 13  당기 1분기 누적    6372 non-null   object
 14  전기 1분기 3개월   6342 non-null   object
 15  전기 1분기 누적    6343 non-null   object
 16  전기           9109 non-null   object
 17  전전기          8976 non-null   object
 18  당기 반기 3개월    6379 non-null   object
 19  당기 반기 누적     6382 non-null   object
 20  전기 반기 3개월    6354 non-null   object
 21  전기 반기 누적     6357 non-null   object
 22  당기 3분기 3개월   5292 non-null   object
 23  당기 3분기 누적    5293 non-null   object
 24  전기 3분기 3개월   5280 non-null   object
 25  전기 3분기 누적    5281 non-null   object
 26  Unnamed: 12  0 non-null      float64
 27  당기           5440 non-null   object
 28  Unnamed: 14  0 non-null      float64
 29  Unnamed: 15  0 non-null      float64
 30  Unnamed: 18  0 non-null      float64
dtypes: float64(4), int64(2), object(25)
memory usage: 5.7+ MB

In [7]:
# 눌값을 다 문자열 0으로 채워줍니다.

df.fillna('0', inplace=True) # inplace = True를 잊으면 안 됩니다!
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23526 entries, 0 to 43401
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   재무제표종류       23526 non-null  object
 1   종목코드         23526 non-null  object
 2   회사명          23526 non-null  object
 3   시장구분         23526 non-null  object
 4   업종           23526 non-null  int64
 5   업종명          23526 non-null  object
 6   결산월          23526 non-null  int64
 7   결산기준일        23526 non-null  object
 8   보고서종류        23526 non-null  object
 9   통화           23526 non-null  object
 10  항목코드         23526 non-null  object
 11  항목명          23526 non-null  object
 12  당기 1분기 3개월   23526 non-null  object
 13  당기 1분기 누적    23526 non-null  object
 14  전기 1분기 3개월   23526 non-null  object
 15  전기 1분기 누적    23526 non-null  object
 16  전기           23526 non-null  object
 17  전전기          23526 non-null  object
 18  당기 반기 3개월    23526 non-null  object
 19  당기 반기 누적     23526 non-null  object
 20  전기 반기 3개월    23526 non-null  object
 21  전기 반기 누적     23526 non-null  object
 22  당기 3분기 3개월   23526 non-null  object
 23  당기 3분기 누적    23526 non-null  object
 24  전기 3분기 3개월   23526 non-null  object
 25  전기 3분기 누적    23526 non-null  object
 26  Unnamed: 12  23526 non-null  object
 27  당기           23526 non-null  object
 28  Unnamed: 14  23526 non-null  object
 29  Unnamed: 15  23526 non-null  object
 30  Unnamed: 18  23526 non-null  object
dtypes: int64(2), object(29)
memory usage: 5.7+ MB

In [8]:
# 현재 금액에 쉼표가 있고 문자열입니다. 쉼표를 없애고 정수형으로 바꿔줍니다. 

for i in df.columns[12:]:
    df[i] = df[i].str.replace(',', '').astype('int64')

In [9]:
# 잘 바뀌었는지 확인해 봅니다. 

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23526 entries, 0 to 43401
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   재무제표종류       23526 non-null  object
 1   종목코드         23526 non-null  object
 2   회사명          23526 non-null  object
 3   시장구분         23526 non-null  object
 4   업종           23526 non-null  int64
 5   업종명          23526 non-null  object
 6   결산월          23526 non-null  int64
 7   결산기준일        23526 non-null  object
 8   보고서종류        23526 non-null  object
 9   통화           23526 non-null  object
 10  항목코드         23526 non-null  object
 11  항목명          23526 non-null  object
 12  당기 1분기 3개월   23526 non-null  int64
 13  당기 1분기 누적    23526 non-null  int64
 14  전기 1분기 3개월   23526 non-null  int64
 15  전기 1분기 누적    23526 non-null  int64
 16  전기           23526 non-null  int64
 17  전전기          23526 non-null  int64
 18  당기 반기 3개월    23526 non-null  int64
 19  당기 반기 누적     23526 non-null  int64
 20  전기 반기 3개월    23526 non-null  int64
 21  전기 반기 누적     23526 non-null  int64
 22  당기 3분기 3개월   23526 non-null  int64
 23  당기 3분기 누적    23526 non-null  int64
 24  전기 3분기 3개월   23526 non-null  int64
 25  전기 3분기 누적    23526 non-null  int64
 26  Unnamed: 12  23526 non-null  int64
 27  당기           23526 non-null  int64
 28  Unnamed: 14  23526 non-null  int64
 29  Unnamed: 15  23526 non-null  int64
 30  Unnamed: 18  23526 non-null  int64
dtypes: int64(21), object(10)
memory usage: 5.7+ MB

In [10]:
# 맨처음 1514개 보다 줄었음을 확인할 수 있습니다.

len(df['종목코드'].unique())

1341

In [11]:
# 우리한테 필요한 열만 가져오기 위해 어떤 열들이 있는지 봅니다. 

df.columns

Index(['재무제표종류', '종목코드', '회사명', '시장구분', '업종', '업종명', '결산월', '결산기준일', '보고서종류',
       '통화', '항목코드', '항목명', '당기 1분기 3개월', '당기 1분기 누적', '전기 1분기 3개월',
       '전기 1분기 누적', '전기', '전전기', '당기 반기 3개월', '당기 반기 누적', '전기 반기 3개월',
       '전기 반기 누적', '당기 3분기 3개월', '당기 3분기 누적', '전기 3분기 3개월', '전기 3분기 누적',
       'Unnamed: 12', '당기', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 18'],
      dtype='object')

## 3분기 누적 데이터와 당기 데이터가 같은 행에 있지 않음

In [12]:
## 3분기 데이터와 당기 데이터를 각각 나누고 둘만 붙인 다음에 계산해야 함 - 종목에 맞게 
# 그 다음 원본 데이터에 인덱스를 기준으로 잘 붙여주기 - 당기 인덱스 기준
df['결산년도'] = [i[:4] for i in df['결산기준일']] # 붙여주기 위한 년도 열 생성
df_3Q = df[(df['당기 3분기 누적']>=1) & (df['보고서종류']=='3분기보고서')][['종목코드', '결산년도', '당기 3분기 누적']]
df_4Q = df[(df['당기']>=1) & (df['보고서종류']=='사업보고서')][['종목코드', '결산년도', '결산기준일', '당기']]
#df_3Q = df_3Q[df_3Q['당기 3분기 누적' > 0]]
df_4Q = pd.merge(df_4Q, df_3Q, on=['종목코드', '결산년도'])
df_4Q['4분기 매출'] = df_4Q['당기'] - df_4Q['당기 3분기 누적']
df = pd.merge(df, df_4Q[['종목코드', '결산기준일', '4분기 매출']], how='outer', on=['종목코드', '결산기준일'])
df

,재무제표종류,종목코드,회사명,시장구분,업종,업종명,결산월,결산기준일,보고서종류,통화,...,당기 3분기 누적,전기 3분기 3개월,전기 3분기 누적,Unnamed: 12,당기,Unnamed: 14,Unnamed: 15,Unnamed: 18,결산년도,4분기 매출
0,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[060310],3S,코스닥시장상장법인,262,전자부품 제조업,3,2016-06-30,1분기보고서,KRW,...,0,0,0,0,0,0,0,0,2016,NaN
1,"포괄손익계산서, 기능별 분류(세전기타포괄손익) - 별도재무제표(선택)",[054620],AP시스템,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2016-03-31,1분기보고서,KRW,...,0,0,0,0,0,0,0,0,2016,NaN
2,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[211270],AP위성통신,코스닥시장상장법인,264,통신 및 방송 장비 제조업,12,2016-03-31,1분기보고서,KRW,...,0,0,0,0,0,0,0,0,2016,NaN
3,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[032040],C&S자산관리,코스닥시장상장법인,759,기타 사업지원 서비스업,12,2016-03-31,1분기보고서,KRW,...,0,0,0,0,0,0,0,0,2016,NaN
4,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[130960],CJ E&M,코스닥시장상장법인,602,텔레비전 방송업,12,2016-03-31,1분기보고서,KRW,...,0,0,0,0,0,0,0,0,2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23521,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[024060],흥구석유,코스닥시장상장법인,467,기타 전문 도매업,12,2021-06-30,반기보고서,KRW,...,0,0,0,0,0,0,0,0,2021,NaN
23522,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[010240],흥국,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-06-30,반기보고서,KRW,...,0,0,0,0,0,0,0,0,2021,NaN
23523,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[189980],흥국에프엔비,코스닥시장상장법인,112,비알코올음료 및 얼음 제조업,12,2021-06-30,반기보고서,KRW,...,0,0,0,0,0,0,0,0,2021,NaN
23524,"포괄손익계산서, 기능별 분류(세후기타포괄손익) - 별도재무제표",[037440],희림,코스닥시장상장법인,721,"건축기술, 엔지니어링 및 관련 기술 서비스업",12,2021-06-30,반기보고서,KRW,...,0,0,0,0,0,0,0,0,2021,NaN
23525,"포괄손익계산서, 성격별 분류(세전기타포괄손익) - 별도재무제표(선택)",[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-06-30,반기보고서,KRW,...,0,0,0,0,0,0,0,0,2021,NaN

In [13]:
# 다시 데이터 전처리 작업을 해줍니다. 
df.fillna('0', inplace=True) # inplace = True를 잊으면 안 됩니다!
df['4분기 매출'] = df['4분기 매출'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23526 entries, 0 to 23525
Data columns (total 33 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   재무제표종류       23526 non-null  object
 1   종목코드         23526 non-null  object
 2   회사명          23526 non-null  object
 3   시장구분         23526 non-null  object
 4   업종           23526 non-null  int64
 5   업종명          23526 non-null  object
 6   결산월          23526 non-null  int64
 7   결산기준일        23526 non-null  object
 8   보고서종류        23526 non-null  object
 9   통화           23526 non-null  object
 10  항목코드         23526 non-null  object
 11  항목명          23526 non-null  object
 12  당기 1분기 3개월   23526 non-null  int64
 13  당기 1분기 누적    23526 non-null  int64
 14  전기 1분기 3개월   23526 non-null  int64
 15  전기 1분기 누적    23526 non-null  int64
 16  전기           23526 non-null  int64
 17  전전기          23526 non-null  int64
 18  당기 반기 3개월    23526 non-null  int64
 19  당기 반기 누적     23526 non-null  int64
 20  전기 반기 3개월    23526 non-null  int64
 21  전기 반기 누적     23526 non-null  int64
 22  당기 3분기 3개월   23526 non-null  int64
 23  당기 3분기 누적    23526 non-null  int64
 24  전기 3분기 3개월   23526 non-null  int64
 25  전기 3분기 누적    23526 non-null  int64
 26  Unnamed: 12  23526 non-null  int64
 27  당기           23526 non-null  int64
 28  Unnamed: 14  23526 non-null  int64
 29  Unnamed: 15  23526 non-null  int64
 30  Unnamed: 18  23526 non-null  int64
 31  결산년도         23526 non-null  object
 32  4분기 매출       23526 non-null  int64
dtypes: int64(22), object(11)
memory usage: 6.1+ MB

## 매출열

In [14]:
# 매출열을 계산해줍니다.

df['매출'] = df['당기 1분기 3개월']+df['당기 반기 3개월']+df['당기 3분기 3개월']+df['4분기 매출']

In [15]:
df['매출']

0          5975861071
1         35352899194
2          2236550468
3         48093649629
4        289597782947
             ...
23521     33990295356
23522     24549301249
23523     16956241121
23524     52915571938
23525     14419272683
Name: 매출, Length: 23526, dtype: int64

In [17]:
df.to_excel("총매출데이터.xlsx")

KeyboardInterrupt:

## 최종 매출데이터 구축

In [18]:
# 종목코드, 회사명, 업종명, 결산기준일
df_sale = df[['종목코드', '회사명', '업종명', '결산기준일', '매출']] # 원하는 데이터만 가져오기
df_sale.index = [i for i in range(len(df['매출']))] # index를 새로 지정
df_sale['종목코드'] = [i[1:-1] for i in df_sale['종목코드']] # 종목코드 수정
df_sale['분기'] = pd.PeriodIndex(df_sale['결산기준일'], freq='Q') # 분기 열 만들기 
df_sale

<ipython-input-18-b547c610337b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['종목코드'] = [i[1:-1] for i in df_sale['종목코드']] # 종목코드 수정
<ipython-input-18-b547c610337b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['분기'] = pd.PeriodIndex(df_sale['결산기준일'], freq='Q') # 분기 열 만들기

,종목코드,회사명,업종명,결산기준일,매출,분기
0,060310,3S,전자부품 제조업,2016-06-30,5975861071,2016Q2
1,054620,AP시스템,특수 목적용 기계 제조업,2016-03-31,35352899194,2016Q1
2,211270,AP위성통신,통신 및 방송 장비 제조업,2016-03-31,2236550468,2016Q1
3,032040,C&S자산관리,기타 사업지원 서비스업,2016-03-31,48093649629,2016Q1
4,130960,CJ E&M,텔레비전 방송업,2016-03-31,289597782947,2016Q1
...,...,...,...,...,...,...
23521,024060,흥구석유,기타 전문 도매업,2021-06-30,33990295356,2021Q2
23522,010240,흥국,특수 목적용 기계 제조업,2021-06-30,24549301249,2021Q2
23523,189980,흥국에프엔비,비알코올음료 및 얼음 제조업,2021-06-30,16956241121,2021Q2
23524,037440,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",2021-06-30,52915571938,2021Q2
23525,238490,힘스,특수 목적용 기계 제조업,2021-06-30,14419272683,2021Q2

# 2. 지표데이터 구축

In [19]:
from pykrx import stock
import time
import pandas as pd
import OpenDartReader
import pandas as pd
from tqdm import tqdm
api_key = '6655d5a62b916e96636cab74f8e7e0b05692b825'
dart = OpenDartReader(api_key)

In [20]:
# KOSDAQ 종목코드 조회
stock_code = stock.get_market_ticker_list(date="20210520", market="KOSDAQ")
(stock_code[:6], len(stock_code))

(['060310', '054620', '265520', '211270', '035760', '051500'], 1503)

In [21]:
def asset_f(year, corp_code, report_code):
    fs = dart.finstate_all(corp=corp_code, bsns_year=year, fs_div='OFS', reprt_code=report_code) 
    try:
        equity = int(fs.loc[fs['sj_div'].isin(['BS']) & fs['account_id'].isin(['ifrs-full_Equity']), 'thstrm_amount'].replace(",", "")) # 당기자본(자본총계)
        liability = int(fs.loc[fs['sj_div'].isin(['BS']) & fs['account_id'].isin(['ifrs-full_Liabilities']), 'thstrm_amount'].replace(",", "")) # 당기부채(부채총계)
        assets = equity + liability # 자산총계
        return assets
    except:
        equity = int(fs.loc[fs['sj_div'].isin(['BS']) & fs['account_id'].isin(['ifrs_Equity']), 'thstrm_amount'].replace(",", "")) # 당기자본(자본총계)
        liability = int(fs.loc[fs['sj_div'].isin(['BS']) & fs['account_id'].isin(['ifrs_Liabilities']), 'thstrm_amount'].replace(",", "")) # 당기부채(부채총계)
        assets = equity + liability # 자산총계
        return assets

stock_code = stock.get_market_ticker_list(date="20210520", market="KOSDAQ") # 현재일자 기준 가장 가까운 영업일의 코스닥 상장종목 리스트
res = pd.DataFrame()
start_date = '20170101'
end_date = '20201231'
for ticker in tqdm(stock_code[:100]):
    df1 = stock.get_market_ohlcv_by_date(fromdate=start_date, todate=end_date, ticker=ticker) # 기본
    df2 = stock.get_market_fundamental_by_date(fromdate=start_date, todate=end_date, ticker=ticker) # 계산값
    df = pd.concat([df1, df2], axis=1)
    df = df.assign(종목코드=ticker, 종목명=stock.get_market_ticker_name(ticker))
    res = pd.concat([res, df], axis=0)
    time.sleep(1)
res = res.reset_index()
res

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [04:49<00:00,  2.89s/it]

,날짜,시가,고가,저가,종가,거래량,BPS,PER,PBR,EPS,DIV,DPS,종목코드,종목명
0,2017-01-02,2820,3035,2790,3000,478672,846.0,0.0,3.55,0.0,0.0,0.0,060310,3S
1,2017-01-03,3070,3070,2900,3030,309507,846.0,0.0,3.58,0.0,0.0,0.0,060310,3S
2,2017-01-04,3030,3095,2980,3090,248971,846.0,0.0,3.65,0.0,0.0,0.0,060310,3S
3,2017-01-05,3090,3300,3050,3090,928979,846.0,0.0,3.65,0.0,0.0,0.0,060310,3S
4,2017-01-06,3090,3095,3015,3015,202702,846.0,0.0,3.56,0.0,0.0,0.0,060310,3S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87539,2020-12-23,6744,8514,6744,7160,30380898,2936.0,0.0,2.76,0.0,0.0,0.0,217730,강스템바이오텍
87540,2020-12-24,7222,7231,6673,6727,3581461,2936.0,0.0,2.59,0.0,0.0,0.0,217730,강스템바이오텍
87541,2020-12-28,6744,6797,6372,6417,1446545,2936.0,0.0,2.47,0.0,0.0,0.0,217730,강스템바이오텍
87542,2020-12-29,6390,6682,6390,6585,824485,2936.0,0.0,2.53,0.0,0.0,0.0,217730,강스템바이오텍
87543,2020-12-30,6549,7009,6531,7001,1587752,2936.0,0.0,2.69,0.0,0.0,0.0,217730,강스템바이오텍

In [22]:
res['분기'] = pd.PeriodIndex(res['날짜'], freq='Q')
res

,날짜,시가,고가,저가,종가,거래량,BPS,PER,PBR,EPS,DIV,DPS,종목코드,종목명,분기
0,2017-01-02,2820,3035,2790,3000,478672,846.0,0.0,3.55,0.0,0.0,0.0,060310,3S,2017Q1
1,2017-01-03,3070,3070,2900,3030,309507,846.0,0.0,3.58,0.0,0.0,0.0,060310,3S,2017Q1
2,2017-01-04,3030,3095,2980,3090,248971,846.0,0.0,3.65,0.0,0.0,0.0,060310,3S,2017Q1
3,2017-01-05,3090,3300,3050,3090,928979,846.0,0.0,3.65,0.0,0.0,0.0,060310,3S,2017Q1
4,2017-01-06,3090,3095,3015,3015,202702,846.0,0.0,3.56,0.0,0.0,0.0,060310,3S,2017Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87539,2020-12-23,6744,8514,6744,7160,30380898,2936.0,0.0,2.76,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4
87540,2020-12-24,7222,7231,6673,6727,3581461,2936.0,0.0,2.59,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4
87541,2020-12-28,6744,6797,6372,6417,1446545,2936.0,0.0,2.47,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4
87542,2020-12-29,6390,6682,6390,6585,824485,2936.0,0.0,2.53,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4
87543,2020-12-30,6549,7009,6531,7001,1587752,2936.0,0.0,2.69,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4

In [23]:
res_unique = res.drop_duplicates(['종목코드', '분기'])
res_unique.reset_index(drop=True, inplace=True)  
res_unique

,날짜,시가,고가,저가,종가,거래량,BPS,PER,PBR,EPS,DIV,DPS,종목코드,종목명,분기
0,2017-01-02,2820,3035,2790,3000,478672,846.0,0.0,3.55,0.0,0.0,0.0,060310,3S,2017Q1
1,2017-04-03,2455,2490,2410,2465,145587,846.0,0.0,2.91,0.0,0.0,0.0,060310,3S,2017Q2
2,2017-07-03,2335,2335,2310,2315,58473,846.0,0.0,2.74,0.0,0.0,0.0,060310,3S,2017Q3
3,2017-10-10,1930,2025,1930,1980,182755,695.0,0.0,2.85,0.0,0.0,0.0,060310,3S,2017Q4
4,2018-01-02,1860,1880,1830,1880,157321,695.0,0.0,2.71,0.0,0.0,0.0,060310,3S,2018Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,2019-10-01,11461,12036,11373,11948,297850,2290.0,0.0,5.90,0.0,0.0,0.0,217730,강스템바이오텍,2019Q4
1431,2020-01-02,7177,7266,7036,7213,439584,2290.0,0.0,3.56,0.0,0.0,0.0,217730,강스템바이오텍,2020Q1
1432,2020-04-01,7974,8186,7585,7585,2264845,2290.0,0.0,3.74,0.0,0.0,0.0,217730,강스템바이오텍,2020Q2
1433,2020-07-01,8939,8983,8381,8417,1183411,2936.0,0.0,3.24,0.0,0.0,0.0,217730,강스템바이오텍,2020Q3
1434,2020-10-05,6177,6461,6177,6408,150483,2936.0,0.0,2.47,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4

In [24]:
quater = {'Q1': '11013',
          'Q2': '11012',
          'Q3': '11014',
          'Q4': '11011'}
res_unique['자산'] = ['' for i in range(len(res_unique['분기']))]
for i in tqdm(range(len(res_unique['자산']))):
    try:
        year = str(res_unique['분기'][i])[:4] # 년도 
        c_code = res_unique['종목코드'][i] # 회사 코드
        q_code = quater[str(res_unique['분기'][i])[-2:]] #분기 코드
        res_unique['자산'][i] = asset_f(year, c_code, q_code)
    except:
        res_unique['자산'][i] = ''
res_unique

<ipython-input-24-bbe6871f3576>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_unique['자산'] = ['' for i in range(len(res_unique['분기']))]
  0%|                                                                                         | 0/1435 [00:00<?, ?it/s]<ipython-input-24-bbe6871f3576>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_unique['자산'][i] = ''
C:\Users\CSEL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-24-bbe6871f3576>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_unique['자산'][i] = asset_f(year, c_code, q_code)
100%|██████████████████████████████████████████████████████████████████████████████| 1435/1435 [02:10<00:00, 10.97it/s]

,날짜,시가,고가,저가,종가,거래량,BPS,PER,PBR,EPS,DIV,DPS,종목코드,종목명,분기,자산
0,2017-01-02,2820,3035,2790,3000,478672,846.0,0.0,3.55,0.0,0.0,0.0,060310,3S,2017Q1,
1,2017-04-03,2455,2490,2410,2465,145587,846.0,0.0,2.91,0.0,0.0,0.0,060310,3S,2017Q2,49054556999
2,2017-07-03,2335,2335,2310,2315,58473,846.0,0.0,2.74,0.0,0.0,0.0,060310,3S,2017Q3,51104087324
3,2017-10-10,1930,2025,1930,1980,182755,695.0,0.0,2.85,0.0,0.0,0.0,060310,3S,2017Q4,52640042055
4,2018-01-02,1860,1880,1830,1880,157321,695.0,0.0,2.71,0.0,0.0,0.0,060310,3S,2018Q1,46838569304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,2019-10-01,11461,12036,11373,11948,297850,2290.0,0.0,5.90,0.0,0.0,0.0,217730,강스템바이오텍,2019Q4,98625924731
1431,2020-01-02,7177,7266,7036,7213,439584,2290.0,0.0,3.56,0.0,0.0,0.0,217730,강스템바이오텍,2020Q1,79468466418
1432,2020-04-01,7974,8186,7585,7585,2264845,2290.0,0.0,3.74,0.0,0.0,0.0,217730,강스템바이오텍,2020Q2,75313586814
1433,2020-07-01,8939,8983,8381,8417,1183411,2936.0,0.0,3.24,0.0,0.0,0.0,217730,강스템바이오텍,2020Q3,71606471960
1434,2020-10-05,6177,6461,6177,6408,150483,2936.0,0.0,2.47,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4,68097298510

In [25]:
res_final = pd.merge(res, res_unique, how='left')
res_final.fillna(method='ffill', inplace=True)
res_final['종목분기'] = res_final['종목코드'] + res_final['분기'].astype('string') 
res_final

,날짜,시가,고가,저가,종가,거래량,BPS,PER,PBR,EPS,DIV,DPS,종목코드,종목명,분기,자산,종목분기
0,2017-01-02,2820,3035,2790,3000,478672,846.0,0.0,3.55,0.0,0.0,0.0,060310,3S,2017Q1,,0603102017Q1
1,2017-01-03,3070,3070,2900,3030,309507,846.0,0.0,3.58,0.0,0.0,0.0,060310,3S,2017Q1,,0603102017Q1
2,2017-01-04,3030,3095,2980,3090,248971,846.0,0.0,3.65,0.0,0.0,0.0,060310,3S,2017Q1,,0603102017Q1
3,2017-01-05,3090,3300,3050,3090,928979,846.0,0.0,3.65,0.0,0.0,0.0,060310,3S,2017Q1,,0603102017Q1
4,2017-01-06,3090,3095,3015,3015,202702,846.0,0.0,3.56,0.0,0.0,0.0,060310,3S,2017Q1,,0603102017Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87539,2020-12-23,6744,8514,6744,7160,30380898,2936.0,0.0,2.76,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4,68097298510,2177302020Q4
87540,2020-12-24,7222,7231,6673,6727,3581461,2936.0,0.0,2.59,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4,68097298510,2177302020Q4
87541,2020-12-28,6744,6797,6372,6417,1446545,2936.0,0.0,2.47,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4,68097298510,2177302020Q4
87542,2020-12-29,6390,6682,6390,6585,824485,2936.0,0.0,2.53,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4,68097298510,2177302020Q4
87543,2020-12-30,6549,7009,6531,7001,1587752,2936.0,0.0,2.69,0.0,0.0,0.0,217730,강스템바이오텍,2020Q4,68097298510,2177302020Q4

In [26]:
df_sale['종목분기'] = df_sale['종목코드'] + df_sale['분기'].astype('string')
df_sale.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23526 entries, 0 to 23525
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    23526 non-null  object
 1   회사명     23526 non-null  object
 2   업종명     23526 non-null  object
 3   결산기준일   23526 non-null  object
 4   매출      23526 non-null  int64
 5   분기      23526 non-null  period[Q-DEC]
 6   종목분기    23526 non-null  string
dtypes: int64(1), object(4), period[Q-DEC](1), string(1)
memory usage: 1.4+ MB

<ipython-input-26-a883bc685d6e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['종목분기'] = df_sale['종목코드'] + df_sale['분기'].astype('string')

In [27]:
df_sale.reset_index(drop=True, inplace=True)
res_final.reset_index(drop=True, inplace=True)
df = pd.merge(res_final, df_sale, how='left', on='종목분기')
df

,날짜,시가,고가,저가,종가,거래량,BPS,PER,PBR,EPS,...,종목명,분기_x,자산,종목분기,종목코드_y,회사명,업종명,결산기준일,매출,분기_y
0,2017-01-02,2820,3035,2790,3000,478672,846.0,0.0,3.55,0.0,...,3S,2017Q1,,0603102017Q1,060310,3S,전자부품 제조업,2017-03-31,358702446.0,2017Q1
1,2017-01-03,3070,3070,2900,3030,309507,846.0,0.0,3.58,0.0,...,3S,2017Q1,,0603102017Q1,060310,3S,전자부품 제조업,2017-03-31,358702446.0,2017Q1
2,2017-01-04,3030,3095,2980,3090,248971,846.0,0.0,3.65,0.0,...,3S,2017Q1,,0603102017Q1,060310,3S,전자부품 제조업,2017-03-31,358702446.0,2017Q1
3,2017-01-05,3090,3300,3050,3090,928979,846.0,0.0,3.65,0.0,...,3S,2017Q1,,0603102017Q1,060310,3S,전자부품 제조업,2017-03-31,358702446.0,2017Q1
4,2017-01-06,3090,3095,3015,3015,202702,846.0,0.0,3.56,0.0,...,3S,2017Q1,,0603102017Q1,060310,3S,전자부품 제조업,2017-03-31,358702446.0,2017Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87539,2020-12-23,6744,8514,6744,7160,30380898,2936.0,0.0,2.76,0.0,...,강스템바이오텍,2020Q4,68097298510,2177302020Q4,217730,강스템바이오텍,기초 의약물질 및 생물학적 제제 제조업,2020-12-31,56912500.0,2020Q4
87540,2020-12-24,7222,7231,6673,6727,3581461,2936.0,0.0,2.59,0.0,...,강스템바이오텍,2020Q4,68097298510,2177302020Q4,217730,강스템바이오텍,기초 의약물질 및 생물학적 제제 제조업,2020-12-31,56912500.0,2020Q4
87541,2020-12-28,6744,6797,6372,6417,1446545,2936.0,0.0,2.47,0.0,...,강스템바이오텍,2020Q4,68097298510,2177302020Q4,217730,강스템바이오텍,기초 의약물질 및 생물학적 제제 제조업,2020-12-31,56912500.0,2020Q4
87542,2020-12-29,6390,6682,6390,6585,824485,2936.0,0.0,2.53,0.0,...,강스템바이오텍,2020Q4,68097298510,2177302020Q4,217730,강스템바이오텍,기초 의약물질 및 생물학적 제제 제조업,2020-12-31,56912500.0,2020Q4
87543,2020-12-30,6549,7009,6531,7001,1587752,2936.0,0.0,2.69,0.0,...,강스템바이오텍,2020Q4,68097298510,2177302020Q4,217730,강스템바이오텍,기초 의약물질 및 생물학적 제제 제조업,2020-12-31,56912500.0,2020Q4

In [29]:
df.to_excel('result_1013.xlsx')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87544 entries, 0 to 87543
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      87544 non-null  datetime64[ns]
 1   시가      87544 non-null  int32
 2   고가      87544 non-null  int32
 3   저가      87544 non-null  int32
 4   종가      87544 non-null  int32
 5   거래량     87544 non-null  int32
 6   BPS     87544 non-null  float64
 7   PER     87544 non-null  float64
 8   PBR     87544 non-null  float32
 9   EPS     87544 non-null  float64
 10  DIV     87544 non-null  float32
 11  DPS     87544 non-null  float64
 12  종목코드_x  87544 non-null  object
 13  종목명     87544 non-null  object
 14  분기_x    87544 non-null  period[Q-DEC]
 15  자산      87544 non-null  object
 16  종목분기    87544 non-null  string
 17  종목코드_y  68225 non-null  object
 18  회사명     68225 non-null  object
 19  업종명     68225 non-null  object
 20  결산기준일   68225 non-null  object
 21  매출      68225 non-null  float64
 22  분기_y    68225 non-null  period[Q-DEC]
dtypes: datetime64[ns](1), float32(2), float64(5), int32(5), object(7), period[Q-DEC](2), string(1)
memory usage: 13.7+ MB

In [31]:
# 최종 필요한 데이터를 가져옵니다. 

data = df.dropna(axis=0)[['날짜', '시가', '고가', '종가', '종목코드_y', '매출']]

data['종목코드_y'] = data['종목코드_y'].astype('int')
data.set_index('날짜', inplace=True)
x_var = data[['시가', '고가', '종목코드_y', '매출']]
x_var.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 68225 entries, 2017-01-02 to 2020-12-30
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시가      68225 non-null  int32
 1   고가      68225 non-null  int32
 2   종목코드_y  68225 non-null  int32
 3   매출      68225 non-null  float64
dtypes: float64(1), int32(3)
memory usage: 1.8 MB

In [52]:
y_var = data['종가']
y_var

날짜
2020-09-17     2230
2020-09-18     2235
2020-09-17     9550
2020-09-18     9300
2020-09-17    22950
              ...
2020-09-18     6241
2020-09-17      700
2020-09-18      705
2020-09-17     7019
2020-09-18     6992
Name: 종가, Length: 132, dtype: int32

In [53]:
import warnings
warnings.filterwarnings('ignore')
import glob
import os
import datetime
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from xgboost import plot_importance
from sklearn.metrics import precision_score, recall_score, confusion_matrix, roc_auc_score
from sklearn.metrics import f1_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score
from sklearn import svm

import seaborn as sns; sns.set()

In [54]:
#훈련 세트와 테스트 세트를 나눈다.
#shuffle=False을 설정해 기간이 섞이지 않도록 만든다.
X_train, X_test, y_train, y_test = train_test_split(x_var, 
                                                    y_var, 
                                                    test_size=0.3, 
                                                    shuffle=False, 
                                                    random_state=3)

#훈련 세트와 테스트 세트에 포함된 양성 샘플(up) 비율을 확인한다.
train_count = y_train.count()
test_count = y_test.count()

print('train set label ratio')
print(y_train.value_counts()/train_count)
print('test set label ratio')
print(y_test.value_counts()/test_count)

train set label ratio
2290     0.032609
4350     0.021739
2224     0.021739
17600    0.021739
1470     0.021739
           ...
6640     0.010870
4015     0.010870
1415     0.010870
5290     0.010870
18800    0.010870
Name: 종가, Length: 82, dtype: float64
test set label ratio
2670      0.050
3760      0.050
9250      0.050
700       0.025
16250     0.025
6201      0.025
1720      0.025
694       0.025
2740      0.025
998       0.025
626       0.025
688       0.025
13550     0.025
2860      0.025
7019      0.025
6992      0.025
60521     0.025
3815      0.025
1920      0.025
60130     0.025
240100    0.025
1740      0.025
3320      0.025
4420      0.025
965       0.025
648       0.025
13450     0.025
705       0.025
2000      0.025
6241      0.025
3665      0.025
16050     0.025
4270      0.025
2840      0.025
2780      0.025
235400    0.025
3390      0.025
Name: 종가, dtype: float64

In [108]:
def get_confusion_matrix(y_test, pred):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred, pos_label='positive', average='micro')
    recall = recall_score(y_test, pred,  pos_label='positive', average='micro')
    f1 = f1_score(y_test, pred,   pos_label='positive', average='micro')
    #roc_score = roc_auc_score(y_test, pred,  multi_class='ovr')
    print('confusion matrix')
    print('accuracy:{0:.4f},precision:{1:.4f},recall:{2:.4f},F1:{3:.4f}'.format(accuracy, precision, recall, f1))

In [109]:
xgb_dis = XGBClassifier(n_estimators=400, learning_rate=0.1, max_depth=3)
xgb_dis.fit(X_train, y_train)
xgb_pred = xgb_dis.predict(X_test)

[17:44:30] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [110]:
xgb_dis

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=400, n_jobs=12, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [111]:
print(xgb_dis.score(X_train, y_train))

0.5869565217391305

In [112]:
get_confusion_matrix(y_test, xgb_pred)

confusion matrix
accuracy:0.0000,precision:0.0000,recall:0.0000,F1:0.0000